apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: nodeport-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32100
  selector:
    app: webapp
  type: NodePort
