# Parent image
from ubuntu:jammy

# Install jdk
RUN apt update && \
    apt install -y default-jdk

COPY ./docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

CMD ["-version"]
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]