apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  containers:

  - name: writer
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the writer container > /usr/write/data.txt; sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /usr/write

  - name: reader
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 5; cat /usr/read/data.txt; sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /usr/read/

  volumes:
  - name: shared-data
    emptyDir: {}

    
#  restartPolicy: Never
