---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-1
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-cont
    image: sample/webapp
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-2
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-cont
    image: sample/webapp
    imagePullPolicy: IfNotPresent
